language: node_js
node_js:
  - '10'

sudo: false
dist: xenial

addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

services:
  - xvfb

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 --window-size=750,1334 http://localhost &

install:
  - yarn install --ignore-engines

stages:
  - test
  - name: npm-release
    if: (tag =~ ^v)
  - name: github-releases
    if: (tag =~ ^v)
  - gh-pages release

jobs:
  include:
    - stage: test
      script:
        - yarn test
