language: node_js
node_js:
  - '10'

sudo: false
dist: xenial

addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1921x1080x24"
install:
  - yarn install --ignore-engines

stages:
  - test
  - name: npm-release
    if: (tag =~ ^v)
  - name: github-releases
    if: (tag =~ ^v)
  - gh-pages release

jobs:
  include:
    - stage: test
      script:
        - yarn test
